### ISSUE TITLE
Error detected while processing function <SNR>128_DoComplete

### ISSUE THREAD

**Issue by heavenshell** [girishji/autosuggest.vim#10]
Hi again!

I've got an error when I type `:h vim9@js<Tab>`
(`@js` is a language that does not exist)

```
:h vim9@js
Error detected while processing function <SNR>128_DoComplete:
line    8:
E433: No tags file
```

Expected behavior
```
:h vim9@js                                                            
E433: No tags file
```

https://github.com/girishji/autosuggest.vim/assets/56591/2694d000-4733-4869-8c45-82becc790d38

Default Vim9's pum behavior
```
set wildmenu
set wildoptions+=pum
set wildmode=full
```

https://github.com/girishji/autosuggest.vim/assets/56591/5d1b675d-2e08-47c6-bec4-3ff1ac241677

I think this is expected behavior

Thank you!

**Comment by girishji** [comment]
This is a Vim bug https://github.com/vim/vim/issues/14514

Edit: This is the stack trace as someone mentioned in the comment. Not a bug, as I had previously thought. The behavior is expected.

**Comment by heavenshell** [comment]
Thank you for the answer and reporting to Vim's issues.

Got it. Now I understood it's a stack trace and there is no way to avoid it.

Too many error shows bit a noisy(as I mentioned avobe. Vim's pum show statck trace only 1 time when I hit a `<Tab>` many times) but I think this is very rare case when I hit wrong language

**Comment by girishji** [comment]
It is possible to suppress all errors silently by enclosing in `try catch` block, but I think it is good to report error even though it is annoying.
