### ISSUE TITLE
RFE: bind a key to explicitly show the completion menu (as in "onspace")?

### ISSUE THREAD

**Issue by intelfx** [girishji/autosuggest.vim#11]
Hi,

I'm trying out this plugin and it seems it's just one step away from being what I've really wanted all this time.

Instead of using `options.cmd.onspace` to enumerate all commands that I ever want to come with "auto-auto-completion", would it be possible to bind a key (like <kbd>\<Leader\>Tab</kbd>, or <kbd>S-Tab</kbd>, or just the normal <kbd>Tab</kbd>) to show the completion menu for the current context explicitly?

Of course there is already the built-in Vim completion menu that is spawned via <kbd>Tab</kbd>, but it has different behaviors than the menu that is auto-spawned by this plugin via "onspace". Basically, I want a key to spawn the completion menu but 1) not auto-insert the first match and 2) fuzzily auto-update the menu based on the characters typed after the spawn event.

Would it be possible to do this with autosuggest.vim? Or am I horribly overthinking everything?

**Comment by intelfx** [comment]
I did an ugliest of hacks to kinda sorta emulate what I wanted here (see second mentioned commit, the first one is even uglier) — but it messes up command line rendering and flickers a lot. Any ideas how to do this right?

**Comment by girishji** [comment]
I'll get to this soon. We have a small baby and he needs lots of attention.

**Comment by intelfx** [comment]
No worries at all! Family takes the highest priority :-)

**Comment by girishji** [comment]
Thanks! Please try now. I made `<tab>` do autocomplete when `alwayson` is `false`. It is a new option for cmd-complete (default is 'true'). Only preliminary testing done. Let me know if it misbehaves.

edit: I can include your solution (`<s-tab>`) also, if it helps.
