### ISSUE TITLE
Bug when interacting with vim-dirvish

### ISSUE THREAD

**Issue by EgZvor** [girishji/autosuggest.vim#2]
When using https://github.com/justinmk/vim-dirvish the `/` search is remapped to account for searching file paths

```
nnoremap <buffer> / /\ze[^/]*[/]\=$<Home>
nnoremap <buffer> ? ?\ze[^/]*[/]\=$<Home>
```

defined here https://github.com/justinmk/vim-dirvish/blob/master/ftplugin/dirvish.vim .

It seems to interfere with autosuggest.vim resulting in an error

```
E867: (NFA regexp) Unknown operator '\zk'
```

**Comment by girishji** [comment]
What are the steps to reproduce? I downloaded dirvish but it did not cause error when I searched with `/`. I see a few places where this issue could be coming from but I need to reproduce it.

**Comment by girishji** [comment]
fixed
https://github.com/girishji/autosuggest.vim/commit/04c39700653b196b004755eb65b8295147f1860c
