### ISSUE TITLE
Unwanted screen clearing on complete

### ISSUE THREAD

**Issue by EgZvor** [girishji/autosuggest.vim#3]
I have a couple of mapping that use a pattern of one command to display something with echo and another to choose an element from displayed ones. E. g., 

```vim
nnoremap <leader>b :buffers<cr>:buffer<space>
```

with autosuggest my echoed output is cleared as soon as I type one character.

**Comment by girishji** [comment]
Thanks for reporting this. I was not able to reproduce. Can you remove other plugins from .vimrc and see if it happens? Does this happen always or is it intermittent?


![](https://i.imgur.com/sNEivsh.png)

**Comment by girishji** [comment]
Fixed. Use the `exclude` option. To stop `:buffer` command from being completed:
```
exclude: ['buffer']
```

https://github.com/girishji/autosuggest.vim/commit/4348a12a387fbcdb3172ddb29bb387d7904fa73f

**Comment by girishji** [comment]
You can also try the following
```
:nnoremap <leader>b :AutoSuggestDisable<cr>:buffers<cr>:let nr = input("Which one: ")<Bar>exe $'buffer {nr}'<bar>AutoSuggestEnable<cr>
```
