### ISSUE TITLE
Changing options

### ISSUE THREAD

**Issue by engeljh** [girishji/autosuggest.vim#4]
I'm trying to change the search option alwayson to false.  The only way I can make it work is to change your original code in the autoload directory.  Can you please tell me how to do this in my .vimrc or in an "after" directory?  The rest of my .vimrc is in legacy vimscript.

Many thanks.

**Comment by girishji** [comment]
You can try `VimEnter` event to set it. Let me know if this does not work. I confirmed that `alwayson` works as expected. Here is my configuration:

```
#--------------------
# autosuggest

var options = {
    search: {
        pum: true,
        fuzzy: false,
        hidestatusline: false,
        alwayson: false,
    },
    cmd: {
        enable: true,
        pum: true,
        hidestatusline: false,
        fuzzy: false,
        onspace: ['buffer', 'find']
    }
}
autocmd VimEnter * g:AutoSuggestSetup(options)
```

**Comment by engeljh** [comment]
I pasted this into my .vimrc and put "vim9" in front of the first command.  It doesn't work.  I also tried putting "vim9" in front of the second command; that makes no difference.

Thanks for your help,
Jon
________________________________

**Comment by engeljh** [comment]
I fixed it.  Had to put "vim9" in front of "g:AutoSuggestSetup(options)".

Sorry for bothering you.

Jon
________________________________
