### ISSUE TITLE
respect pumheight

### ISSUE THREAD

**Issue by basilgood** [girishji/autosuggest.vim#5]
Hi, it's possible to add an option for this plugin to respect pumheight or to have the possibility to set pumheight ?
I have ```set pumheight=5``` but it is taken into account only after I type ```<Tab>```.
Search suggestions respect pumheight but cmdline suggestions not.
Thank you.

**Comment by girishji** [comment]
Fixed by commit f77c2ac. Thanks for reporting the bug.
