### ISSUE TITLE
popup menu flickers

### ISSUE THREAD

**Issue by Song-Tianxiang** [girishji/autosuggest.vim#6]
The completion window flickers seriously, is there any way to alleviate it?

**Comment by girishji** [comment]
What command are you trying to complete?

If this is related to file completion, and you have thousands of files then it is explainable. Vim redraws the popup window when you update it through async search.

You can also exclude commands from completion.

**Comment by Song-Tianxiang** [comment]
I feel like redraw occurs every time I type a character.

**Comment by girishji** [comment]
If I were to guess you are seeing screen flicker in commands (`:`) but not while searching (`/`). If so, it is an artifact of `wildmenu` completion. I don't notice flicker usually as I have a fast computer, but I can see if I observe carefully. It is possible to eliminate flicker completely by replacing wildmenu/pmenu popup with newer popup_create(). I'll put this on my todo list. You are the first one who raised this issue.

**Comment by Song-Tianxiang** [comment]
> If I were to guess you are seeing screen flicker in commands (`:`) but not while searching (`/`). 

you are right. flicker occurs in `:` not `/`.
`/` works fine, no flicker.

**Comment by girishji** [comment]
I could not muster enough motivation to do this enhancement (since it does not bother me). I also have a small kid and finding time is not easy. I am closing this since there is no point keeping this open.

**Comment by Song-Tianxiang** [comment]
I truly understand you and also appreciate your contributions to the Vim plugin community. If anyone wishes to solve this issue, this [plugin](https://github.com/Shougo/pum.vim) might be useful.
