### ISSUE TITLE
Behavior when set same characters in exclude and onspace

### ISSUE THREAD

**Issue by heavenshell** [girishji/autosuggest.vim#9]
Hi, First of all thank you for creating an awesome plugin!

I use `:e` a lot.
When I type `:e`, I get a lot of candidates and it feels bit a noisy, so I add `exclude: ['e']`.
This works fine for me, but I want to see file or directory candidates after enter `:e<SPACE>`.
So I set `onspace: ['e']`.

But onspace did not show candidates after I input `<SPACE>`.

If I type like `:e<SPACE><TAB>` this shows candidates but first item was selected.
I just want to show candidates(The behavior I want is same as `set completeopt noselect,noinsert`).
Is there any way to show candidates only?(`:e<SPACE><C-D>` shows candidates but did not popup)

Below is screencast.

- Type `:e<SPACE>`
- Candidates are shown but filled cmdline area with LICENSE
- I just want to see candidates
- Hit `<C-d>` shows candidates but not popup

https://github.com/girishji/autosuggest.vim/assets/56591/a50bfc58-88f2-4c15-a65b-c9eb04fe27ec

**Comment by girishji** [comment]
Can you please try:
```
            exclude: ['^e$'],
            onspace: ['e'],
```

'exclude' is a regex pattern match, not string comparison. You have to exclude `:e` while not excluding `:e<space>`

**Comment by heavenshell** [comment]
Thank you for so much!
Works fine!
